# Generated by Django 6.0.3 on 2026-04-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_matiere'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Matiere',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='prenom',
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
