# Generated by Django 6.0.3 on 2026-04-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='coefficient',
            field=models.IntegerField(default=1),
        ),
    ]
