# Generated by Django 6.0.4 on 2026-04-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_alter_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
