# Generated by Django 6.0.4 on 2026-04-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='school_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
