# Generated by Django 6.0.3 on 2026-04-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_school_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='school_name',
        ),
    ]
